name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: VictorHugo-Rodrigues
          github_repository_name: VictorHugo-Rodrigues
          outputs: gif
